version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./users.db:/app/users.db
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    environment:
      - NODE_ENV=development
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://api:5000
    restart: always
