# SUPPRIMEZ la ligne version: '3.8'

services:
  backend:
    build: .
    backend:
    ports:
      - '5000:5000'
    volumes:
      - ./users.db:/app/users.db
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    environment:
      - NODE_ENV=development
    restart: always

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    restart: always
