name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Installer les dépendances (backend)
      - name: Install backend dependencies
        run: |
          cd user_managment
          npm install

      # 4. Lancer les tests (si définis)
      - name: Run tests
        run: |
          cd user_managment
          npm test || echo "Tests non définis ou échoués"

      # 5. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.safiabelasi }}/user-management-app 

      # 6. Connexion à Docker Hub
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.safiabelasri }}" --password-stdin

      # 7. Push image vers Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.safiabelasri }}/user-management-app

      # 8. (Optionnel) Déploiement via SSH sur un serveur VPS
      - name: Deploy to VPS (via SSH)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.safiabelasri }}/user-management-app
            docker stop user-management || true
            docker rm user-management || true
            docker run -d --name user-management -p 5000:5000 ${{ secrets.safiabelasri }}/user-management-app
